services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mini-service-desk
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./docker/entrypoint.sh:/entrypoint.sh
    working_dir: /var/www/html
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
